# Generated by Django 4.2.4 on 2023-08-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_rename_emial_appointment_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default=943332341, max_length=50),
            preserve_default=False,
        ),
    ]
